"use client";

import React, { useState, useRef, useEffect, MouseEvent as ReactMouseEvent, TouchEvent as ReactTouchEvent } from "react";

interface MeshPoint {
  id: string;
  color: string;
  x: number; // 0 to 100
  y: number; // 0 to 100
  size: number; // 10 to 100
}

export default function GradientMesh() {
  const [points, setPoints] = useState<MeshPoint[]>([
    { id: "1", color: "#f97316", x: 20, y: 20, size: 60 },
    { id: "2", color: "#00a2f4", x: 80, y: 40, size: 70 },
    { id: "3", color: "#9d4300", x: 40, y: 80, size: 55 },
    { id: "4", color: "#cde5ff", x: 10, y: 90, size: 65 },
  ]);
  const [selectedPointId, setSelectedPointId] = useState<string>("1");
  const [isCopied, setIsCopied] = useState<boolean>(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const dragInfo = useRef<{ pointId: string } | null>(null);

  const getGradientCss = () => {
    const gradients = points.map(
      (p) => `radial-gradient(circle at ${p.x}% ${p.y}%, ${p.color} 0%, transparent ${p.size}%)`
    );
    return `background-color: #000000;\nbackground-image:\n  ${gradients.join(",\n  ")};`;
  };

  const selectedPoint = points.find((p) => p.id === selectedPointId) || points[0];

  const updateSelectedPoint = (key: keyof MeshPoint, value: string | number) => {
    setPoints((prev) =>
      prev.map((p) => (p.id === selectedPointId ? { ...p, [key]: value } : p))
    );
  };

  const handleAddPoint = () => {
    if (points.length >= 10) {
      alert("You cannot add more than 10 pins!");
      return;
    }
    const newId = (Math.max(...points.map((p) => parseInt(p.id))) + 1).toString();
    const newPoint: MeshPoint = {
      id: newId,
      color: "#" + Math.floor(Math.random() * 16777215).toString(16).padStart(6, "0"),
      x: Math.floor(Math.random() * 60) + 20,
      y: Math.floor(Math.random() * 60) + 20,
      size: 50,
    };
    setPoints((prev) => [...prev, newPoint]);
    setSelectedPointId(newId);
  };

  const handleRemovePoint = () => {
    if (points.length <= 1) {
      alert("Please keep at least one pin!");
      return;
    }
    const remaining = points.filter((p) => p.id !== selectedPointId);
    setPoints(remaining);
    setSelectedPointId(remaining[0].id);
  };

  const handleDragStart = (pointId: string, e: ReactMouseEvent | ReactTouchEvent) => {
    e.stopPropagation();
    setSelectedPointId(pointId);
    dragInfo.current = { pointId };
  };

  const handleDragMove = (clientX: number, clientY: number) => {
    if (!dragInfo.current || !containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    
    let x = ((clientX - rect.left) / rect.width) * 100;
    let y = ((clientY - rect.top) / rect.height) * 100;

    x = Math.max(0, Math.min(100, Math.round(x)));
    y = Math.max(0, Math.min(100, Math.round(y)));

    const activeId = dragInfo.current.pointId;
    setPoints((prev) =>
      prev.map((p) => (p.id === activeId ? { ...p, x, y } : p))
    );
  };

  const handleMouseMove = (e: MouseEvent) => {
    if (!dragInfo.current) return;
    handleDragMove(e.clientX, e.clientY);
  };

  const handleTouchMove = (e: TouchEvent) => {
    if (!dragInfo.current || e.touches.length === 0) return;
    handleDragMove(e.touches[0].clientX, e.touches[0].clientY);
  };

  const handleDragEnd = () => {
    dragInfo.current = null;
  };

  useEffect(() => {
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", handleDragEnd);
    window.addEventListener("touchmove", handleTouchMove, { passive: false });
    window.addEventListener("touchend", handleDragEnd);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseup", handleDragEnd);
      window.removeEventListener("touchmove", handleTouchMove);
      window.removeEventListener("touchend", handleDragEnd);
    };
  });

  const handleCopyCode = async () => {
    try {
      const cssCode = `/* CSS Gradient Mesh Generated by ToolUndo */\n.mesh-gradient {\n  ${getGradientCss().replace(/\n/g, "\n  ")}\n}`;
      await navigator.clipboard.writeText(cssCode);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
      alert("Failed to copy text!");
    }
  };

  const getInlineStyle = () => {
    const gradients = points.map(
      (p) => `radial-gradient(circle at ${p.x}% ${p.y}%, ${p.color} 0%, transparent ${p.size}%)`
    );
    return {
      backgroundColor: "#000000",
      backgroundImage: gradients.join(", "),
    };
  };

  return (
    <div className="bg-surface swiss-border rounded-lg p-6 md:p-8 flex flex-col gap-6 w-full max-w-5xl mx-auto shadow-sm">
      <div className="flex flex-col gap-2">
        <h2 className="font-headline-sm text-headline-sm text-on-surface flex items-center gap-sm">
          <span className="material-symbols-outlined text-primary-container">gradient</span>
          CSS Mesh Gradient Studio
        </h2>
        <p className="font-body-sm text-body-sm text-secondary">
          Mix colors to create a stunning background. Drag and drop the pins on the canvas to experiment!
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Visual Interactive Canvas */}
        <div className="lg:col-span-7 flex flex-col gap-4">
          <div
            ref={containerRef}
            style={getInlineStyle()}
            className="w-full aspect-video md:aspect-4/3 rounded-lg swiss-border relative overflow-hidden shadow-inner cursor-crosshair custom-gradient-mesh select-none"
          >
            <div className="absolute inset-0 grid grid-cols-6 grid-rows-6 pointer-events-none opacity-[0.03] border-collapse">
              {Array.from({ length: 36 }).map((_, i) => (
                <div key={i} className="border border-on-surface"></div>
              ))}
            </div>

            {/* Draggable Pins */}
            {points.map((p) => (
              <div
                key={p.id}
                onMouseDown={(e) => handleDragStart(p.id, e)}
                onTouchStart={(e) => handleDragStart(p.id, e)}
                style={{ left: `${p.x}%`, top: `${p.y}%` }}
                className={`absolute -translate-x-1/2 -translate-y-1/2 w-7 h-7 rounded-full border-2 cursor-grab active:cursor-grabbing flex items-center justify-center transition-transform hover:scale-110 shadow-md ${
                  selectedPointId === p.id
                    ? "border-primary-container bg-white ring-4 ring-primary-container/20 scale-105 z-30"
                    : "border-white bg-slate-700 hover:bg-slate-800 z-20"
                }`}
              >
                <span
                  style={{ backgroundColor: p.color }}
                  className="w-3.5 h-3.5 rounded-full block border border-outline-variant"
                ></span>
              </div>
            ))}
          </div>

          <div className="flex justify-between items-center bg-surface-container-low p-3 rounded border border-outline-variant text-xs text-secondary font-mono">
            <span>✨ Drag or click points on the canvas to reposition</span>
            <span>Total Stops: {points.length}/10</span>
          </div>
        </div>

        {/* Sidebar Controls Panel */}
        <div className="lg:col-span-5 flex flex-col gap-5">
          {/* Point Selector Pills */}
          <div className="flex flex-col gap-2">
            <span className="font-body-sm text-on-surface font-semibold text-xs">Select Pin Point</span>
            <div className="flex flex-wrap gap-2">
              {points.map((p, idx) => (
                <button
                  key={p.id}
                  onClick={() => setSelectedPointId(p.id)}
                  className={`px-3 py-1.5 rounded text-xs font-semibold font-mono flex items-center gap-1.5 border transition-all ${
                    selectedPointId === p.id
                      ? "border-primary-container bg-primary-container/10 text-primary"
                      : "border-outline-variant text-secondary bg-surface hover:bg-surface-container-low"
                  }`}
                >
                  <span
                    style={{ backgroundColor: p.color }}
                    className="w-2.5 h-2.5 rounded-full border border-outline-variant/50"
                  ></span>
                  Pin {idx + 1}
                </button>
              ))}
              <button
                onClick={handleAddPoint}
                disabled={points.length >= 10}
                className="px-3 py-1.5 rounded text-xs font-semibold bg-surface-container-highest border border-outline-variant text-on-surface hover:bg-outline-variant/30 transition-all flex items-center gap-1 disabled:opacity-40"
              >
                <span className="material-symbols-outlined text-[16px]">add</span> Add New
              </button>
            </div>
          </div>

          {/* Current Stop Controls */}
          <div className="border border-outline-variant rounded-lg p-4 flex flex-col gap-4 bg-surface-container-lowest">
            <div className="flex justify-between items-center pb-2 border-b border-outline-variant/40">
              <span className="font-body-md text-on-surface font-bold text-xs uppercase tracking-wider">
                Pin Settings
              </span>
              <button
                onClick={handleRemovePoint}
                className="text-xs text-error font-semibold hover:underline flex items-center gap-0.5"
              >
                <span className="material-symbols-outlined text-[14px]">delete</span> Delete Pin
              </button>
            </div>

            {/* Color Stop Picker */}
            <div className="flex items-center justify-between">
              <label htmlFor="mesh-color" className="font-body-sm text-on-surface font-semibold text-xs">
                Pin Color
              </label>
              <div className="flex items-center gap-2">
                <input
                  id="mesh-color"
                  type="color"
                  value={selectedPoint?.color || "#000000"}
                  onChange={(e) => updateSelectedPoint("color", e.target.value)}
                  className="w-8 h-8 border border-outline-variant rounded cursor-pointer p-0"
                />
                <input
                  type="text"
                  value={selectedPoint?.color || ""}
                  onChange={(e) => updateSelectedPoint("color", e.target.value)}
                  className="w-20 border border-outline-variant rounded px-2 py-0.5 font-mono text-xs uppercase text-on-surface"
                />
              </div>
            </div>

            {/* Radial Spread Size */}
            <div className="flex flex-col gap-1.5">
              <div className="flex justify-between text-xs">
                <label htmlFor="mesh-size" className="font-body-sm text-on-surface font-semibold">
                  Radius Spread
                </label>
                <span className="font-mono font-bold text-secondary">{selectedPoint?.size || 50}%</span>
              </div>
              <input
                id="mesh-size"
                type="range"
                min="10"
                max="120"
                value={selectedPoint?.size || 50}
                onChange={(e) => updateSelectedPoint("size", parseInt(e.target.value))}
                className="w-full h-1.5 bg-outline-variant rounded-lg accent-primary-container cursor-pointer"
              />
            </div>

            {/* Coordinate Inputs */}
            <div className="grid grid-cols-2 gap-4">
              {/* X coordinate */}
              <div className="flex flex-col gap-1">
                <div className="flex justify-between text-xs">
                  <label htmlFor="mesh-x" className="font-body-sm text-on-surface font-semibold text-[11px]">
                    Horizontal (X)
                  </label>
                  <span className="font-mono text-secondary text-[11px]">{selectedPoint?.x || 0}%</span>
                </div>
                <input
                  id="mesh-x"
                  type="range"
                  min="0"
                  max="100"
                  value={selectedPoint?.x || 0}
                  onChange={(e) => updateSelectedPoint("x", parseInt(e.target.value))}
                  className="w-full h-1.5 bg-outline-variant rounded-lg accent-primary-container cursor-pointer"
                />
              </div>

              {/* Y coordinate */}
              <div className="flex flex-col gap-1">
                <div className="flex justify-between text-xs">
                  <label htmlFor="mesh-y" className="font-body-sm text-on-surface font-semibold text-[11px]">
                    Vertical (Y)
                  </label>
                  <span className="font-mono text-secondary text-[11px]">{selectedPoint?.y || 0}%</span>
                </div>
                <input
                  id="mesh-y"
                  type="range"
                  min="0"
                  max="100"
                  value={selectedPoint?.y || 0}
                  onChange={(e) => updateSelectedPoint("y", parseInt(e.target.value))}
                  className="w-full h-1.5 bg-outline-variant rounded-lg accent-primary-container cursor-pointer"
                />
              </div>
            </div>
          </div>

          {/* Export Code button */}
          <div className="flex flex-col gap-2 mt-auto">
            <button
              onClick={handleCopyCode}
              className="w-full bg-primary-container text-white py-3 px-4 rounded font-label-caps text-label-caps uppercase tracking-wider font-bold hover:bg-primary transition-all duration-200 active:scale-95 flex items-center justify-center gap-xs shadow-sm"
            >
              <span className="material-symbols-outlined text-[18px]">
                {isCopied ? "check" : "content_copy"}
              </span>
              {isCopied ? "Copied to Clipboard!" : "Copy CSS Code"}
            </button>
          </div>
        </div>
      </div>

      {/* Code Preview Box */}
      <div className="mt-2 border border-outline-variant rounded-lg overflow-hidden bg-surface-container-low font-mono text-xs">
        <div className="flex justify-between items-center px-4 py-2 border-b border-outline-variant/60 bg-surface-container-high text-secondary">
          <span>Generated CSS Code</span>
          <span className="text-[10px] bg-primary-container/15 text-primary-container px-2 py-0.5 rounded uppercase font-bold">
            Pure CSS
          </span>
        </div>
        <pre className="p-4 text-on-surface overflow-x-auto whitespace-pre leading-relaxed select-all">
{`.mesh-gradient {
  background-color: #000000;
  background-image:
    ${points.map((p) => `radial-gradient(circle at ${p.x}% ${p.y}%, ${p.color} 0%, transparent ${p.size}%)`).join(",\n    ")};
}`}
        </pre>
      </div>
    </div>
  );
}